-- ============================================================
-- SEIMEI - SUNA : MODULE CAMP DE REDRESSEMENT (v3)
-- À exécuter UNE FOIS dans l'éditeur SQL du projet Supabase, après
-- SQL_psy.sql et SQL_psy_v2.sql.
--
-- Ajoute : une catégorie "camp_redressement" sur les suivis, une
-- affiliation "camp de redressement" sur les comptes psychologues, et
-- l'évaluation initiale QCM (20 questions, 1 à 3 points chacune) dont
-- le score détermine automatiquement l'état mental / niveau de
-- dangerosité — d'après la grille de la Cellule Psychologique de
-- Sunagakure.
-- ============================================================

-- --- Catégorie de suivi : standard ou camp de redressement ---
alter table psy_suivis add column if not exists categorie text not null default 'standard'
  check (categorie in ('standard', 'camp_redressement'));

-- --- Affiliation "camp de redressement" d'un psychologue ---
alter table psy_membres add column if not exists camp_redressement_affilie boolean not null default false;

-- ============================================================
-- Évaluations initiales "Camp de redressement" (QCM 20 questions)
-- ============================================================
create table if not exists psy_camp_evaluations (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),

  suivi_id bigint references psy_suivis(id) on delete cascade,
  patient_id bigint references psy_patients(id) on delete set null,
  patient_nom text not null,

  psy_id uuid references psy_membres(id) on delete set null,
  psy_nom text,

  -- [{ question: "...", reponse: "...", points: 1|2|3 }, ...]
  reponses jsonb not null default '[]'::jsonb,

  score_total int not null,
  etat_mental text not null,
  niveau_dangerosite text not null check (niveau_dangerosite in ('faible_modere', 'modere_eleve', 'eleve'))
);

create index if not exists idx_psy_camp_evaluations_suivi on psy_camp_evaluations (suivi_id);
create index if not exists idx_psy_camp_evaluations_patient on psy_camp_evaluations (patient_id);

alter table psy_camp_evaluations enable row level security;
drop policy if exists "anon_all_psy_camp_evaluations" on psy_camp_evaluations;
create policy "anon_all_psy_camp_evaluations" on psy_camp_evaluations for all to anon using (true) with check (true);

-- --- Journalisation automatique (Gérance) ---
alter table psy_activity_log drop constraint if exists psy_activity_log_action_type_check;
alter table psy_activity_log add constraint psy_activity_log_action_type_check
  check (action_type in
    ('test', 'evaluation', 'suivi_creation', 'suivi_statut', 'rapport_seance', 'autotest_traite', 'evaluation_camp'));

create or replace function log_psy_camp_evaluation() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into psy_activity_log (membre_id, membre_nom, action_type, target_table, target_id, patient_nom, resume)
  values (new.psy_id, new.psy_nom, 'evaluation_camp', 'psy_suivis', new.suivi_id, new.patient_nom,
          'Évaluation initiale Camp de redressement — ' || new.etat_mental || ' (' || new.score_total || ' pts)');
  return new;
end;
$$;
drop trigger if exists trg_log_psy_camp_evaluation on psy_camp_evaluations;
create trigger trg_log_psy_camp_evaluation after insert on psy_camp_evaluations
  for each row execute function log_psy_camp_evaluation();
