-- ============================================================
-- SEIMEI - SUNA : ÉVALUATIONS PSYCHOLOGIQUES
-- Historique partagé entre psychologues (barème officiel /52)
-- ============================================================
create table if not exists psy_evaluations (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),

  -- Identité du patient évalué
  patient_nom text not null,
  patient_grade text,
  patient_unite text,
  patient_age int,
  patient_sexe text,

  -- Évaluateur et date de l'entretien
  evaluateur text,
  date_evaluation date,

  -- Détail du barème (6.2)
  score_criteres int,      -- 8 critères x 5 pts  -> 0 à 40
  score_situations int,    -- 3 mises en situation x 3 pts -> 0 à 9
  score_impression int,    -- première impression : -1 / 0 / +1
  total_bonus int,         -- bonus cliniques plafonnés à +2
  total_malus int,         -- malus diagnostiques cumulables
  total_ajustements int,   -- ajustements « Autre »

  -- Résultat final (6.3)
  score_final int,         -- 0 à 52
  decision text,

  -- Réponses complètes : notes par critère, notes des mises en
  -- situation, diagnostics et bonus retenus, justifications
  reponses jsonb
);

create index if not exists idx_psy_evaluations_nom on psy_evaluations (lower(patient_nom));
create index if not exists idx_psy_evaluations_date on psy_evaluations (created_at desc);

alter table psy_evaluations enable row level security;

drop policy if exists "Accès public psy_evaluations" on psy_evaluations;
create policy "Accès public psy_evaluations" on psy_evaluations
  for all using (true) with check (true);


-- ============================================================
-- SEIMEI - SUNA : AUTO-TESTS PATIENTS
-- Tri auto-administré (sans psychologue) — le patient ne voit
-- jamais son score, seulement le message qualitatif associé.
-- Pas d'impression clinique / bonus / malus : jugement clinique
-- non disponible en auto-évaluation.
-- ============================================================
create table if not exists psy_autotests (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),

  -- Identité déclarée par le patient
  patient_nom text not null,
  patient_grade text,
  patient_age int,
  patient_sexe text,

  -- Détail du barème (auto-évalué, sans impression/bonus/malus)
  score_criteres int,      -- 8 critères x 5 pts  -> 0 à 40
  score_situations int,    -- 3 mises en situation x 3 pts -> 0 à 9
  score_final int,         -- 0 à 49 (critères + situations)
  decision text,           -- tranche calculée via getDecisionForScore()

  -- Réponses complètes : notes par critère et par mise en situation
  reponses jsonb,

  -- Suivi psychologue : cas signalé pris en charge ou non
  traite boolean not null default false,
  traite_par text,
  traite_le timestamptz
);

create index if not exists idx_psy_autotests_nom on psy_autotests (lower(patient_nom));
create index if not exists idx_psy_autotests_date on psy_autotests (created_at desc);
create index if not exists idx_psy_autotests_traite on psy_autotests (traite);

alter table psy_autotests enable row level security;

drop policy if exists "Accès public psy_autotests" on psy_autotests;
create policy "Accès public psy_autotests" on psy_autotests
  for all using (true) with check (true);
