-- ============================================================
-- SEIMEI - SUNA : BACK-OFFICE BRANCHE PSYCHOLOGIQUE (v2)
-- À exécuter UNE FOIS dans l'éditeur SQL du projet Supabase
-- (ltqltvfjpczdstkfrwpo), après SQL_psy.sql (psy_evaluations /
-- psy_autotests doivent déjà exister).
--
-- Ce script ajoute : comptes individuels (psy_membres), fiche
-- patient unique (psy_patients), registre des tests légers
-- (psy_tests), suivi psychologique (psy_suivis), rapports de
-- séance (psy_rapports_seance), communications internes
-- restreintes (psy_communications), documents (procédures /
-- formation) et tarifs, et un journal d'activité alimenté
-- automatiquement par triggers (aucune saisie manuelle).
-- ============================================================


-- ============================================================
-- 1. psy_membres — comptes individuels des psychologues
-- ============================================================
create table if not exists psy_membres (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),

  nom text not null,
  prenom text not null,
  sceau text not null,             -- hash SHA-256 (jamais le mot de passe en clair)

  role text not null default 'psychologue'
    check (role in ('psychologue', 'gerance_psy', 'seimei')),
  categorie text not null default 'branche_psy_uniquement'
    check (categorie in ('seimei_medical_psy', 'branche_psy_uniquement')),
  statut text not null default 'en_attente'
    check (statut in ('en_attente', 'actif', 'inactif'))
);

create unique index if not exists idx_psy_membres_identite
  on psy_membres (lower(nom), lower(prenom));

alter table psy_membres enable row level security;

drop policy if exists "anon_select_psy_membres" on psy_membres;
create policy "anon_select_psy_membres" on psy_membres for select to anon using (true);
drop policy if exists "anon_insert_psy_membres" on psy_membres;
create policy "anon_insert_psy_membres" on psy_membres for insert to anon with check (true);
drop policy if exists "anon_update_psy_membres" on psy_membres;
create policy "anon_update_psy_membres" on psy_membres for update to anon using (true) with check (true);

-- Personne (même avec la clé publique) ne peut lire le sceau directement.
revoke select (sceau) on psy_membres from anon, authenticated;

-- Connexion : compare le sceau côté serveur, ne renvoie jamais sa valeur,
-- et ne renvoie rien si le compte n'est pas encore activé par la Gérance.
create or replace function verifier_sceau_psy(p_nom text, p_prenom text, p_sceau_hash text)
returns table (
  id uuid, nom text, prenom text, role text, categorie text, statut text, created_at timestamptz
)
language sql
security definer
set search_path = public
stable
as $$
  select m.id, m.nom, m.prenom, m.role, m.categorie, m.statut, m.created_at
  from psy_membres m
  where lower(m.nom) = lower(p_nom)
    and lower(m.prenom) = lower(p_prenom)
    and m.sceau = p_sceau_hash
    and m.statut = 'actif'
  limit 1;
$$;

revoke all on function verifier_sceau_psy(text, text, text) from public;
grant execute on function verifier_sceau_psy(text, text, text) to anon;


-- ============================================================
-- 2. psy_patients — fiche patient unique (find-or-create)
-- ============================================================
create table if not exists psy_patients (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),

  nom text not null,
  grade text,
  unite text,
  age int,
  sexe text
);

create unique index if not exists idx_psy_patients_nom on psy_patients (lower(nom));

alter table psy_patients enable row level security;
drop policy if exists "anon_all_psy_patients" on psy_patients;
create policy "anon_all_psy_patients" on psy_patients for all to anon using (true) with check (true);

-- Retrouve un patient par nom (insensible à la casse) ou le crée s'il
-- n'existe pas encore, et renvoie sa fiche à jour (grade/unité/âge/sexe
-- rafraîchis si fournis). Utilisé par tests/suivis/évaluations pour ne
-- jamais dupliquer un patient.
create or replace function find_or_create_psy_patient(
  p_nom text, p_grade text default null, p_unite text default null,
  p_age int default null, p_sexe text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  select id into v_id from psy_patients where lower(nom) = lower(p_nom) limit 1;
  if v_id is null then
    insert into psy_patients (nom, grade, unite, age, sexe)
    values (p_nom, p_grade, p_unite, p_age, p_sexe)
    returning id into v_id;
  else
    update psy_patients set
      grade = coalesce(p_grade, grade),
      unite = coalesce(p_unite, unite),
      age = coalesce(p_age, age),
      sexe = coalesce(p_sexe, sexe)
    where id = v_id;
  end if;
  return v_id;
end;
$$;

revoke all on function find_or_create_psy_patient(text, text, text, int, text) from public;
grant execute on function find_or_create_psy_patient(text, text, text, int, text) to anon;


-- ============================================================
-- 3. psy_tests — registre léger (Kensatsu / Camp / BDM / Autre)
-- ============================================================
create table if not exists psy_tests (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),

  patient_id bigint references psy_patients(id) on delete set null,
  patient_nom text not null,

  type text not null check (type in ('kensatsu', 'camp_redressement', 'bdm', 'autre')),
  date_passation date not null default current_date,

  psy_id uuid references psy_membres(id) on delete set null,
  psy_nom text,

  motif text,
  resultat text,
  statut text not null default 'a_revoir'
    check (statut in ('apte', 'inapte', 'a_revoir', 'sous_surveillance')),
  piece_jointe_url text
);

create index if not exists idx_psy_tests_patient on psy_tests (patient_id);
create index if not exists idx_psy_tests_date on psy_tests (date_passation desc);
create index if not exists idx_psy_tests_type on psy_tests (type);

alter table psy_tests enable row level security;
drop policy if exists "anon_all_psy_tests" on psy_tests;
create policy "anon_all_psy_tests" on psy_tests for all to anon using (true) with check (true);


-- ============================================================
-- 4. psy_suivis — suivi psychologique (actif / pause / inactif)
-- ============================================================
create table if not exists psy_suivis (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),

  patient_id bigint references psy_patients(id) on delete set null,
  patient_nom text not null,

  psy_referent_id uuid references psy_membres(id) on delete set null,
  psy_referent_nom text,
  co_referent_nom text,

  motif_entree text,
  frequence text,

  statut text not null default 'actif' check (statut in ('actif', 'pause', 'inactif')),
  motif_pause text,
  motif_cloture text,

  date_debut date not null default current_date,
  date_cloture date,

  historique_statuts jsonb not null default '[]'::jsonb
);

create index if not exists idx_psy_suivis_patient on psy_suivis (patient_id);
create index if not exists idx_psy_suivis_statut on psy_suivis (statut);
create index if not exists idx_psy_suivis_referent on psy_suivis (psy_referent_id);

alter table psy_suivis enable row level security;
drop policy if exists "anon_all_psy_suivis" on psy_suivis;
create policy "anon_all_psy_suivis" on psy_suivis for all to anon using (true) with check (true);


-- ============================================================
-- 5. psy_rapports_seance — rapport structuré après chaque séance
-- ============================================================
create table if not exists psy_rapports_seance (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),

  suivi_id bigint references psy_suivis(id) on delete cascade,
  patient_id bigint references psy_patients(id) on delete set null,
  patient_nom text not null,

  psy_id uuid references psy_membres(id) on delete set null,
  psy_nom text,

  date_seance date not null default current_date,
  duree_minutes int,

  humeur text check (humeur in ('stable', 'instable', 'degradee', 'en_amelioration')),
  niveau_risque text not null default 'aucun'
    check (niveau_risque in ('aucun', 'a_surveiller', 'preoccupant', 'urgent')),
  coherence_discours text,

  resume text,
  objectifs_abordes text,
  recommandations text,
  prochaine_seance date
);

create index if not exists idx_psy_rapports_suivi on psy_rapports_seance (suivi_id);
create index if not exists idx_psy_rapports_patient on psy_rapports_seance (patient_id);
create index if not exists idx_psy_rapports_date on psy_rapports_seance (date_seance desc);
create index if not exists idx_psy_rapports_risque on psy_rapports_seance (niveau_risque);

alter table psy_rapports_seance enable row level security;
drop policy if exists "anon_all_psy_rapports_seance" on psy_rapports_seance;
create policy "anon_all_psy_rapports_seance" on psy_rapports_seance for all to anon using (true) with check (true);


-- ============================================================
-- 6. psy_communications — fil restreint Gérance/Seimei en écriture
-- ============================================================
create table if not exists psy_communications (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),

  auteur_id uuid references psy_membres(id) on delete set null,
  auteur_nom text,

  titre text not null,
  contenu text not null,
  epingle boolean not null default false
);

create index if not exists idx_psy_communications_date on psy_communications (created_at desc);

alter table psy_communications enable row level security;
drop policy if exists "anon_select_psy_communications" on psy_communications;
create policy "anon_select_psy_communications" on psy_communications for select to anon using (true);
-- Pas de policy insert/update/delete pour anon : tout passe par le RPC ci-dessous,
-- seul chemin qui vérifie réellement le rôle côté serveur.

-- Publie une communication seulement si l'auteur est actif et a le rôle
-- gerance_psy ou seimei — vérifié côté Postgres, donc réellement infalsifiable
-- (contrairement au reste du site où les permissions ne sont que côté client).
create or replace function publier_communication(
  p_auteur_id uuid, p_sceau_hash text, p_titre text, p_contenu text, p_epingle boolean default false
)
returns psy_communications
language plpgsql
security definer
set search_path = public
as $$
declare
  v_membre psy_membres;
  v_row psy_communications;
begin
  select * into v_membre from psy_membres
    where id = p_auteur_id and sceau = p_sceau_hash and statut = 'actif';

  if v_membre.id is null then
    raise exception 'Authentification invalide.';
  end if;

  if v_membre.role not in ('gerance_psy', 'seimei') then
    raise exception 'Seule la Gérance ou la Seimei peut publier une communication.';
  end if;

  insert into psy_communications (auteur_id, auteur_nom, titre, contenu, epingle)
  values (p_auteur_id, v_membre.prenom || ' ' || v_membre.nom, p_titre, p_contenu, p_epingle)
  returning * into v_row;

  return v_row;
end;
$$;

revoke all on function publier_communication(uuid, text, text, text, boolean) from public;
grant execute on function publier_communication(uuid, text, text, text, boolean) to anon;

-- Supprime une communication (mêmes règles que la publication).
create or replace function supprimer_communication(p_id bigint, p_auteur_id uuid, p_sceau_hash text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_membre psy_membres;
begin
  select * into v_membre from psy_membres
    where id = p_auteur_id and sceau = p_sceau_hash and statut = 'actif';

  if v_membre.id is null or v_membre.role not in ('gerance_psy', 'seimei') then
    raise exception 'Action non autorisée.';
  end if;

  delete from psy_communications where id = p_id;
end;
$$;

revoke all on function supprimer_communication(bigint, uuid, text) from public;
grant execute on function supprimer_communication(bigint, uuid, text) to anon;


-- ============================================================
-- 7. psy_documents — Procédures & Formation (édition Gérance/Seimei
--    côté UI ; pas d'enjeu de confidentialité comme les communications)
-- ============================================================
create table if not exists psy_documents (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),

  categorie text not null check (categorie in ('procedure', 'formation')),
  titre text not null,
  contenu text,
  ordre int not null default 0,
  updated_by_nom text
);

create index if not exists idx_psy_documents_categorie on psy_documents (categorie, ordre);

alter table psy_documents enable row level security;
drop policy if exists "anon_all_psy_documents" on psy_documents;
create policy "anon_all_psy_documents" on psy_documents for all to anon using (true) with check (true);


-- ============================================================
-- 8. psy_tarifs — tableau des tarifs (lecture publique)
-- ============================================================
create table if not exists psy_tarifs (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),

  prestation text not null,
  prix text not null,
  ordre int not null default 0
);

alter table psy_tarifs enable row level security;
drop policy if exists "anon_all_psy_tarifs" on psy_tarifs;
create policy "anon_all_psy_tarifs" on psy_tarifs for all to anon using (true) with check (true);


-- ============================================================
-- 9bis. Rattache psy_evaluations / psy_autotests aux comptes individuels
--       pour un journal d'activité fiable (sans dépendre du texte libre)
-- ============================================================
alter table psy_evaluations add column if not exists psy_id uuid references psy_membres(id) on delete set null;
alter table psy_evaluations add column if not exists patient_id bigint references psy_patients(id) on delete set null;
alter table psy_autotests add column if not exists traite_par_id uuid references psy_membres(id) on delete set null;
alter table psy_autotests add column if not exists patient_id bigint references psy_patients(id) on delete set null;


-- ============================================================
-- 9. psy_activity_log — journal d'activité (rempli PAR TRIGGERS,
--    jamais par le code front : aucune ligne ne peut être "oubliée")
-- ============================================================
create table if not exists psy_activity_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),

  membre_id uuid references psy_membres(id) on delete set null,
  membre_nom text,

  action_type text not null check (action_type in
    ('test', 'evaluation', 'suivi_creation', 'suivi_statut', 'rapport_seance', 'autotest_traite')),
  target_table text not null,
  target_id bigint,
  patient_nom text,
  resume text
);

create index if not exists idx_psy_activity_membre on psy_activity_log (membre_id, created_at desc);
create index if not exists idx_psy_activity_date on psy_activity_log (created_at desc);

alter table psy_activity_log enable row level security;
drop policy if exists "anon_select_psy_activity_log" on psy_activity_log;
create policy "anon_select_psy_activity_log" on psy_activity_log for select to anon using (true);
-- Pas de policy insert pour anon : seuls les triggers (security definer
-- implicite : ils tournent avec les droits du propriétaire de la table
-- déclenchante) peuvent écrire ici.

-- --- Triggers de journalisation automatique ---

create or replace function log_psy_test() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into psy_activity_log (membre_id, membre_nom, action_type, target_table, target_id, patient_nom, resume)
  values (new.psy_id, new.psy_nom, 'test', 'psy_tests', new.id, new.patient_nom,
          initcap(replace(new.type, '_', ' ')) || ' — ' || coalesce(new.statut, ''));
  return new;
end;
$$;
drop trigger if exists trg_log_psy_test on psy_tests;
create trigger trg_log_psy_test after insert on psy_tests
  for each row execute function log_psy_test();

create or replace function log_psy_evaluation() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into psy_activity_log (membre_id, membre_nom, action_type, target_table, target_id, patient_nom, resume)
  values (new.psy_id, new.evaluateur, 'evaluation', 'psy_evaluations', new.id, new.patient_nom,
          'Entretien clinique complet — ' || coalesce(new.decision, '') || ' (' || coalesce(new.score_final::text, '?') || '/52)');
  return new;
end;
$$;
drop trigger if exists trg_log_psy_evaluation on psy_evaluations;
create trigger trg_log_psy_evaluation after insert on psy_evaluations
  for each row execute function log_psy_evaluation();

create or replace function log_psy_suivi() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    insert into psy_activity_log (membre_id, membre_nom, action_type, target_table, target_id, patient_nom, resume)
    values (new.psy_referent_id, new.psy_referent_nom, 'suivi_creation', 'psy_suivis', new.id, new.patient_nom,
            'Ouverture du suivi (' || coalesce(new.statut, 'actif') || ')');
  elsif tg_op = 'UPDATE' and new.statut is distinct from old.statut then
    insert into psy_activity_log (membre_id, membre_nom, action_type, target_table, target_id, patient_nom, resume)
    values (new.psy_referent_id, new.psy_referent_nom, 'suivi_statut', 'psy_suivis', new.id, new.patient_nom,
            'Statut du suivi : ' || old.statut || ' -> ' || new.statut);
  end if;
  return new;
end;
$$;
drop trigger if exists trg_log_psy_suivi on psy_suivis;
create trigger trg_log_psy_suivi after insert or update on psy_suivis
  for each row execute function log_psy_suivi();

create or replace function log_psy_rapport_seance() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  -- target_table/target_id pointent vers le SUIVI (pas le rapport lui-même)
  -- pour que le lien "voir" en Gérance ouvre directement la fiche de suivi.
  insert into psy_activity_log (membre_id, membre_nom, action_type, target_table, target_id, patient_nom, resume)
  values (new.psy_id, new.psy_nom, 'rapport_seance', 'psy_suivis', new.suivi_id, new.patient_nom,
          'Rapport de séance — risque : ' || coalesce(new.niveau_risque, 'aucun'));
  return new;
end;
$$;
drop trigger if exists trg_log_psy_rapport_seance on psy_rapports_seance;
create trigger trg_log_psy_rapport_seance after insert on psy_rapports_seance
  for each row execute function log_psy_rapport_seance();

create or replace function log_psy_autotest_traite() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.traite = true and (old.traite is distinct from new.traite) then
    insert into psy_activity_log (membre_id, membre_nom, action_type, target_table, target_id, patient_nom, resume)
    values (new.traite_par_id, new.traite_par, 'autotest_traite', 'psy_autotests', new.id, new.patient_nom, 'Auto-test marqué comme traité');
  end if;
  return new;
end;
$$;
drop trigger if exists trg_log_psy_autotest_traite on psy_autotests;
create trigger trg_log_psy_autotest_traite after update on psy_autotests
  for each row execute function log_psy_autotest_traite();
